#=================================================
#   Description: Build rpi3b FROM LEAN'S LEDE
#   Author: Henry
#=================================================

name: Build rpi3b

on: 
  release:
    types: [published]
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler u-boot-tools
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede lede
        cd lede
        echo "src-git lienol https://github.com/Lienol/openwrt-package" >> feeds.conf.default
        git clone https://github.com/BoringCat/luci-app-mentohust package/luci-app-mentohust
        git clone https://github.com/KyleRicardo/MentoHUST-OpenWrt-ipk package/mentohust
        git clone https://github.com/tty228/luci-app-serverchan package/luci-app-serverchan
        git clone https://github.com/rufengsuixing/luci-app-adguardhome package/luci-app-adguardhome
        git clone https://github.com/brokeld/luci-app-koolproxyR package/luci-app-koolproxyR
        git clone https://github.com/openwrt-dev/po2lmo.git
        rm -rf package/lean/luci-theme-argon
        git clone https://github.com/jerrykuku/luci-theme-argon.git package/lean/luci-theme-argon
        pushd po2lmo

    - name: Update feeds
      run: cd lede && ./scripts/feeds update -a

    - name: Install feeds
      run: cd lede && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        cp -f rpi3b.config ./lede/.config
        chmod +x diy.sh
        cd lede
        ../diy.sh
        make defconfig

    - name: Download package
      run: |
        echo -e "$(nproc) thread build."
        cd lede && make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build
      run: |
        cd lede
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: RPI3B
        path: ./lede/bin
